# Site settings
title: PRML

email: "imagineer1981@gmail.com"
url: "http://cwh1981.github.io"
github_url: "https://github.com/cwh1981/mathematicalmonk"
github_editurl: "/blob/gh-pages"
github_profile: "http://github.com/cwh1981"
baseurl: "/prml"
disqus_shortname: norman3github

exclude:
  - README.md
  - _site
  
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
