# Site settings
title: MathematicalMonk ML

email: "imagineer1981@gmail.com"
url: "https://cwh1981.github.io/"
github_url: "https://github.com/cwh1981/mathematicalmonk"
github_editurl: "/blob/gh-pages"
github_profile: "https://github.com/cwh1981"
baseurl: "/mathematicalmonk"
disqus_shortname: cwh1981github

exclude:
  - README.md
  - _site
  
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
